# Generated by Django 4.2.6 on 2023-10-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('time_add', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(choices=[(0, 'На модерации'), (1, 'Опубликовано')], default=0)),
                ('photo', models.ImageField(upload_to='static/images/%Y/%m/%d', verbose_name='Фото')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.category')),
            ],
            options={
                'ordering': ['-time_add'],
            },
        ),
    ]
