# Generated by Django 4.2.6 on 2023-10-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
    ]
