# Generated by Django 4.2.6 on 2023-10-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_alter_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_published',
            new_name='is_available',
        ),
    ]
